### ISSUE TITLE
[Epic/META] Ability for managers to offer an honorarium

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2074]
- [ ] Needs issue template filled @Erioldoesdesign 

**Is your feature request related to a problem? Please describe.**

**Is your feature request related to an existing functionality? Please describe.**

A clear and concise description of what or where the existing page or function is. Include URLs.

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Include ideal URLs, if they don't already exist.

**Describe alternatives you've considered**

**Additional context**

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Applicants

**Ideal deadline**

Recommend review in Q2 rebasing for priority level.

---
Below are a historic list of functions, capabilities, ideas and acceptance criteria for the over 'Epic/META' of this feature.

Admin/manager

- [ ] Option to enable somewhere in admin/settings or env var
- [ ] Creates a new apply > menu item
- [ ] List of existing providers
- [ ] Ability to add/edit provider (Name, URL, help URL, status [enabled/disabled])
- [ ] For each provider, the ability to add/load tokens (upload a csv file)
- [ ] Ability to see information about each provider (tokens available, tokens issued, date added, status)
- [ ] Option to select which "Screening" statues receive an honorarium automatically
- [ ] A threshold setting for warning when tokens are low

Application editors

- [ ] New "Honorarium" form option is available to be included for all applications, the applicant has the option to choose any one of the enabled providers

Applicant

- [ ] Ability to choose an honorarium from the list of enabled providers when applying (see https://apply.reset.tech/reset-our-future-fund/)
- [ ] On first determination, the applicant receives a new email letting them know they have an honoraria to claim
- [ ] On the application page, a new box "Honorarium", listing their chosen provider with the option to change provider or claim their honorarium. 
- [ ] Change, presents an option for them to chose from any enabled provider
- [ ] Claim, presents them a token, URL, and help URL, a confirm 
- [ ] When confirmed, they no longer see the option change but have the option to view their confirmed selection again

Backend considerations

- [ ] Mapping confirmed token to the applicant, no double issuing

**Comment by danblah** [comment]
Ahh, gonna refine this to make use of https://docs.voucherify.io/reference

**Comment by Erioldoesdesign** [comment]
Q1 2022 Rebasing updates:
* Removed from milestones https://github.com/HyphaApp/hypha/milestones/Backlog
* Removed from project board 'backlog' 
* Added the issue template to body without content yet and assigned Eriol to issue to fill at a later date.
* This is not a single issue, it's an Epic/META. - **PM needed to build out Epic/META details**
* Converted to an EPIC in Zenhub extension.
* Size estimated at XL
* Removed priority low label
* Added to forum post for Ideation meeting topics: https://we.hypha.app/t/candidate-topics-for-ideation-sessions-for-pinning/341
* Recommend review in Q2 rebasing for priority level.
