### ISSUE TITLE
[Epic] Redesign Filters

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2501]
## User story

As a user there is no way to save regularly used filter views. Users suggested they used other tools to save lists of links to view the same page with different filters applied. Users also need to manually zoom out of the page to click the 'filter' button.
![Screenshot 2021-06-15 09 15 17](https://user-images.githubusercontent.com/620336/122059320-7ece6a00-cdba-11eb-99ac-e7563a5f6cd3.png)

I completely ripped off [BT's designs from a past discussion](https://github.com/HyphaApp/hypha/discussions/2278) and pasted it here. @ei8fdb was inspired while shopping for clothes online.

As a user, I would like:
- [ ] see more filter options by clicking on "Show all filters"
- [ ] filtered views that can be saved and shared amongst the team?

## Describe the solution you'd like in Hypha

1. The user uses the filters to choose that fund, application status, etc they want to view. 

![109986969-20dfb000-7cfe-11eb-93ed-90aa0a3388f2](https://user-images.githubusercontent.com/20019656/130239584-3c61c823-9e0a-4012-b084-4bbfdc28e532.jpg)

2. If they want to see more filters, they click "Show all filters" - with this they can filter further:
![list-view-2](https://user-images.githubusercontent.com/1899506/109987077-381e9d80-7cfe-11eb-9a41-9af1066442d8.jpg)

3. When the press filter, the subset of applications is shown:
![list-view-3](https://user-images.githubusercontent.com/1899506/109987264-61d7c480-7cfe-11eb-89c0-2c692385b2e5.jpg)

4. If the user wants to search for, say a particular reviewer use the search box and the results are shown:
![list-view-4](https://user-images.githubusercontent.com/1899506/109987568-a7948d00-7cfe-11eb-81de-73d93cef1685.jpg)

---
## Internal Approval Process
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [x] Di to help organise testing/feedback session with OTF users
- [x] @OpenTechFund/design do testing/feedback session with OTF users
- [ ] OTF to sign-off
- [ ] @OpenTechFund/design to make sure most up to date designs designs are attached to issue
