### ISSUE TITLE
[Meta] Improve user account management in WagTail

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2815]
## Summary

Make it easier to manage user accounts and their permissions on Hypha

## Description

Staff Admin and Admin roles need a central location to manage user accounts and permissions on Hypha. Staff Admin and Admin role should be able to search, count, and better monitor permissions of all individuals and groups on Hypha. 

## Proposed Solution 

A central control panel for managing permissions. A central panel already exists, but functionalities are not available to manage data access. These controls are limited to access within the WagTail Admin. 

![Screenshot 2022-04-20 8 28 15 PM](https://user-images.githubusercontent.com/20019656/164298168-99eda0b8-9c50-486f-8d73-2e9e0903ccce.png)

Reviewer Settings control access to data, but only for Reviewers

![image](https://user-images.githubusercontent.com/20019656/164298684-1a9c7307-0e0e-425a-b9c6-a91c4bf84bb4.png)

User Roles has filters for searching, tallying, and narrowing down groups and individuals. We are doing continued work on improving this interface.

![image](https://user-images.githubusercontent.com/20019656/164299090-619fa4de-76cf-49e2-b937-42f2934f6fa1.png)

## Related Issues

- [ ] Combine or minimize how many user roles are available (or better document roles and their permissions) https://github.com/HyphaApp/hypha/issues/2814
- [ ] More straightfoward method to ensure user roles have access to data https://github.com/HyphaApp/hypha/issues/2168
- [ ] https://github.com/HyphaApp/hypha/issues/2793
- [ ] https://github.com/HyphaApp/hypha/issues/2792

---
## Internal Approval Process
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [x] Di to help organise testing/feedback session with OTF users
- [x] @OpenTechFund/design do testing/feedback session with OTF users
- [ ] OTF to sign-off
- [ ] @OpenTechFund/design to make sure most up to date designs designs are attached to issue
