### ISSUE TITLE
[Meta] Improve Reviewer role experience

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2816]
## Summary
'Reviewer' user role and group includes Advisory Council Members, Board Members, vounteer reviewers, peer reviewers for participatory funders. This role could view and submit reviews for submissions and submission outcomes, but is unable to access permissions on the platform beyond this like the staff user role.

## Description
This epic is a collection of features and enhancements to improve the Reviewer user experience on Hypha. 

## Proposed Solution

- [x] [Reviewers are different than staff and should be able to complete a different review template when evaluating an application](https://github.com/HyphaApp/hypha/issues/2273)
- [ ] [An application moves from External Reviewer to the next workflow status based on the reviewer's outcome](https://github.com/HyphaApp/hypha/issues/2535)
- [ ] Provided with better guidance for when they have already [submitted a review or when a review is in draft form](https://github.com/HyphaApp/hypha/issues/2738)
- [ ] [Reviewers will be able to receive a summary of results and outcomes as an external output outside of Hypha](https://github.com/HyphaApp/hypha/issues/2328)
- [ ] [Reviewers could see results and outcomes of proposals in bulk](https://github.com/HyphaApp/hypha/issues/2492)
