### ISSUE TITLE
[Epic] Improve apply form for applicants

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2817]
## Description
The application is the primary connection an applicant has to a funding organization. This epic aims to improve the applicant's user workflow to minimize friction and ensure applicants receive the information they need to complete the application process. 

### Input fields

- [ ] https://github.com/HyphaApp/hypha/issues/1992

### Applicants could preview submissions 
- [x] #1876 

### Automatically add Wagtail system required field when creating new application forms

- [ ] https://github.com/HyphaApp/hypha/issues/2275
- [ ] https://github.com/HyphaApp/hypha/issues/2460

### Split application forms into sections

- [ ] https://github.com/HyphaApp/hypha/issues/1961
- [ ] https://github.com/HyphaApp/hypha/issues/2378
- [ ] https://github.com/HyphaApp/hypha/issues/1951

### Provide images and graphics

- [ ] https://github.com/HyphaApp/hypha/issues/2506

### User Log-in Information

- [ ] https://github.com/HyphaApp/hypha/issues/2758

### Applicant access to applications/dashboard/platform

- [ ] A partner is a role that could be assigned to an application and could function as another user account associated a specific application. [This feature would ensure this role has access to an application as it moves through the system in multiple stages ](https://github.com/HyphaApp/hypha/issues/1138)
