### ISSUE TITLE
[EPIC]: Accessibility improvements of form fields

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2895]
- [ ] Wrap multiple radio and checkbox input fields in fieldsets. Replace use of label with legend as section header.
- [x] #2899
- [ ] Make button hover states easily visible. Upload button e.g. has a hard to see hover state.
- [ ] Make hover and focus state the same for all buttons and links.
- [ ] Add aria-required="true" to all required fields.
- [ ] Link help text form__help with field with help of aria-describedby="id-of-help-text".
- [ ] Mark invalid fields with aria-invalid="true".
- [ ] Set focus to first field with error.
- [ ] Add a subtle highlight to label plus checkbox/radio on hover/focus. Make it easy for users to see what they are about to click on.
- [ ] Add hover/foucs state to all link on forms. E.g the "See help guide…"

**Comment by fourthletter** [comment]
Could we make the borders lighter? We often group multiple choice questions together so the application will show a series of boxes stacked up if we implement darker borders.

Lighter Border
![image](https://user-images.githubusercontent.com/20019656/177519456-6b612ec9-1fac-474b-8209-fa5df6757bec.png)



Darker Border
![image](https://user-images.githubusercontent.com/20019656/177519867-a65d631e-0deb-42c3-80d1-0522a66ff8b6.png)
