### ISSUE TITLE
[Epic] Implement Hypha Compliance and Finance Workflow

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2911]
(This issue is a work-in-progress) 

## User story

> As a funded project, I want to receive and sign my contract so that I can start work I am being funded for.

## Users involved
- Contractor
- Programme Manager (PM) 
- Compliance Attorney (CA)
- General Council (GC)
- Finance Director (FD)
- Chief Executive Officer (CEO) 
- Vice President (VP)

### Compliance Proposal Approval Process

- [X] #2904 PM can create and submit Project Approval Form (PAF)
- [X] #2914 Compliance Attorney can review Project Approval Form
- [X] #2915 Compliance Attorney can request changes to Project Approval Form
- [X] #2916 Approver user group can request changes to Project Approval Form
- [X] #2913 Approver user group role can approve the Project Approval Form
- [x] #2912 Add SOW template

### Contracting

- [x] #2917 Contractor can request changes to the contract

### Payment Information

- [x] #2921 Optional vendor creation step to payment information

### Invoicing 

- [x] #2918 Remove Finance 2 user from workflow

### Possible sub-issues

- [x] #2919 How the PAF progress looks in the Activity Feed
- [x] #2882 Make default email notifications to all users
- [x] #2920  User notifications on Compliance Proposal Approval Process transition
- [X] #2925  Contracting Role: PAF to approve table 
- [x] #2924  Staff Role: PAF submitted table 
- [x] #2923  Approver Role: PAF to approve table 
- [x] #2922  Finance needs to view invoices on a table/dashboard 

#### Questions
Does the PAF need to be in a frozen state?
How to ensure version control for contracts submitted by contractor? Date and timestamp? 
What does Compliance need to download? PAF, SOW, and approvals. What does this look like?
