### ISSUE TITLE
[Epic] How the PAF progress looks in Hypha activity feed view

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2919]
## Additional context
This is a sub-issue of #2911 

### Description
This issue is to show how the PAF progress looks in the activity feed.

- [x] PM submits completed PAF for approval from CA
- [x] CA requests more information
- [x] CA submits PAF to CEO, Finance, Compliance for approval
- [x] CEO, Finance, Compliance request change
- [x] CEO, Finance, Compliance for approval
- [ ] Contract approved/signed/mutually executed 

-- both CEO and contractor signed contract (I think we need to show this, but not sure right now. Unsure if we need to display contract has been signed. **We need to find out if contract needs to be displayed**).

## Priority
- High (keeping you from completing day-to-day tasks)

## Ideal deadline
October 2022

**Comment by sandeepsajan0** [comment]
**Record**: It is already done by an unknown PR. As it is tested and approved for live means it is already on test, so closing this issue.
