### ISSUE TITLE
[Epic] Organise Hypha settings in Wagtail admin

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2981]
Main goals are:

* Custom Wagtail admin front page with quick access to most used functions.
* Separate Custom Hypha and Wagtail core settings
* Move all Hypha setting in to "Apply" and "Project" meny sections.

- [x] Rename "Manage" to "Project" 
- [x] Move "Project Approval Forms" from  "Apply" to "Project" 
- [ ] Move all Hypha settings from "Settings" to either  "Apply" or "Project" menu sections.

Do we need more sections? Should some settings be in the root menu?

Hypha settings are:

* Projects settings
* Determination messages
* Reviewer settings
* Application settings
* PDF settings
* System settings
* Vendor Form settings
* User settings

Ignore all things related to the "public" site, this will be removed in the future.

**Comment by fourthletter** [comment]
Thank you! ⚡ 

![image](https://user-images.githubusercontent.com/20019656/200847058-32c76f46-3ed9-47fe-99f2-ac932e7d0974.png)
