### ISSUE TITLE
[Epic] DRAFT Application User Journey

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2982]
Main goals are:

* Better manage draft submissions in Hypha
* Staff user role does not have oversight and information to provide applicants with tech support related to their draft applications
* Draft applications are in parallel with submitted applications, applicants have the same questions and concerns, but there is a lack of user research on this process

## New
- [x] For logged in applicant, messaging after an application submission as draft #3556
- [x] Lab can't be saved as draft if required fields are not filled #3555
- [x] Draft editing doesn't allow saving without filling in required fields #3554

## Completed
- [x] Move DRAFT submissions on funds to current round #3105
- [x]  The setting SUBMISSIONS_DRAFT_ACCESS_STAFF_ADMIN does not act on submission table only detail view #3146
- [x] Remove slack alerts and notifications for DRAFT submissions #3021
- [x] Applicants saving a draft does not receive an email notification #2940
- [x] Timestamp on draft submissions should be date submitted (not date created) #2854
- [x]  Add a setting that decides if STAFF ADMIN can see draft submissions or not #3013
- [x]  Add a setting that decides if staff can see draft submissions or not #2986
- [X] https://github.com/HyphaApp/hypha/issues/1532
- [X] https://github.com/HyphaApp/hypha/issues/1523

Related
https://github.com/HyphaApp/hypha/issues/309
