### ISSUE TITLE
[EPIC] Bells, Whistles, and the Activity Feed 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3085]
## Description 

Communication and notifications keep external stakeholders informed, and ensure program managers/staff are able to track applications and projects within Hypha. Documentation will cover different communication channels designated for conveying information internally and externally, including how various components on the user interface interact with WagTail settings. 

### General Overview
https://docs.hypha.app/developers/notifications/

### Email
https://docs.hypha.app/administrators/configuration/#e-mail-settings
https://docs.hypha.app/developers/notifications/#translation-localization-files-for-automated-messages -- **IS THIS CORRECT???**

### Slack
https://docs.hypha.app/administrators/configuration/
https://github.com/HyphaApp/hypha/issues/2852

### Automated Notifications
https://docs.hypha.app/administrators/configuration/#if-automatic-e-mails-should-be-sent-out-to-reviewers-when-submissions-are-ready-for-review

### Projects Page (invoice/contract) Notifications
https://docs.hypha.app/developers/notifications/#notifications-and-reminders-for-invoicing-and-contracting

## Missing

- [ ] In-App Notifications
https://github.com/HyphaApp/hypha/pull/2892
- [ ] User Settings/Website Settings
- [ ] Additional text for automated messages
- [ ] Comment/Communication tab
