### ISSUE TITLE
[EPIC] Compliance/Finance Workflow Winter Sprint

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3181]
(This issue is a work-in-progress) 

## User story

> As a funded project, I want to receive and sign my contract so that I can start work I am being funded for.

## Users involved
- Contractor
- Programme Manager (PM) 
- Compliance Attorney (CA)
- General Council (GC)
- Finance Director (FD)
- Chief Executive Officer (CEO) 
- Vice President (VP)
- Applicant

### Compliance Proposal Approval Process

- [x] Notify applicant that a project has been created for their submission. #3171 🔔 
- [x] staff + approver role can not see the approve the PAF button #3199
- [x] [All roles] New dashboard on 'My dashboard' for contracting and invoicing #3534
- [x] [Contracting Role] New table for PAF #3535
- [x] [Staff Role] Table on Project Page #3536
- [x] [Applicant] Add invoice table to Applicant dashboard #3207

### Contracting

- [x] Contracting, Applicant, Staff, and Finance's dashboard updates for Contracting and In Progress projects #3165
- [x] Upload contract doc title preview #3166
- [x] Contract document error #3167
- [x] Notify applicant that the contract has been approved and they can start submitting invoices #3174 🔔 
- [x] Remove the red banner telling applicant that the project can not be edited #3175
- [x] Hide the “Corrections or amendments to your contract?” when the contract is approved. #3176
- [x] Make it more obvious for a applicant where to see/download the contract #3180
- [x] Contracting should not have access to the project after the contract is approved. #3205
- [x] Applicant needs to recieve email notification when their project has been approved #3204 🔔 

### Payment Information

- [x] Add ability to upload templates for each type of project supporting document #3189
- [X] Update the flow for collecting banking details #3212

### Invoicing 

- [x] On staff dashboard rename "Active invoices" to "Invoices awaiting your review" #3177
- [x] On applicant dashboard remove the Fund allocation column #3179
- [x] Add notification via e-mail to finance when staff have approved an invoice #3178 🔔 
- [ ] Improve usability of picklist on project page #3208
- [x] Improve Applicant dashboard for invoicing #3207
- [x] Improve usability of the dashboard invoicing #3206

### Usability/UX 
- [x] Compliance and finance workflow testing #3558
- [x] Improve hierarchy of various buttons/options on project page #3203
- [x] Show on-screen alerts to notify the users when the action has taken place #3202
- [x] Improve usability of interface and workflow of the Action to Take box with buttons #3197
- [x] Duplicate buttons on project page user interface #3196
- [x] Enhance visibility for selecting a Lead on projects page #3193
- [x] Improve visibility of PAF fill in #3191
- [x] Improve usability of “create project” button #3190

## Sub-issues

- [x] Add drag and drop widget for upload files wherever it is missing #3200
- [x] Add a loader when it takes some time for the file to be uploaded #3201
- [x] Input field on form does not allow bullet points #3195
- [x] Front end validation of number fields etc. #3194
- [x] Make approval form required when creating a fund application #3192

**Comment by sandeepsajan0** [comment]
@frjo I think we can close this one. Because only one issue is open and that too is also not a priority. So we can keep that issue open in the backlog but may close this epic?
