### ISSUE TITLE
[EPIC] Compliance/Finance Workflow Spring Sprint

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3261]
(This issue is a work-in-progress) 

## User story

> As a funded project, I want to receive and sign my contract so that I can start work I am being funded for.

## Users involved
- Contractor
- Programme Manager (PM) 
- Compliance Attorney (CA)
- General Council (GC)
- Finance Director (FD)
- Chief Executive Officer (CEO) 
- Vice President (VP)
- Applicant

### PAF Approval Process

- [ ] How the PAF progress looks on the project page #3256
- [ ] Program Manager assigns PAF to Approver, Finance, Contracting user groups #3258
- [ ] Add SOW template to wagtail #3259
- [ ] CEO gives PAF final approval #3260
