### ISSUE TITLE
[Epic] Registration Form

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3443]
### Description

As an applicant I need to register and login into the platform. The current registration form does not contain the details I need to register for this site. 

### Example Registration
![image](https://github.com/HyphaApp/hypha/assets/20019656/47ce0a8e-9049-468f-8ce5-3dc80e69fbb3)

### GitHub Issues

- [x] NEW registered users are routed to their dashboard to apply rather than to their profile page
- [x] Always send e-mail after non logged in users apply or create an account #3370
- [x] Alternative workflows for registration https://github.com/HyphaApp/hypha/pull/3156
- [x] remove registration/login from nav bar https://github.com/HyphaApp/hypha/pull/3156
- [x] Update authentication https://github.com/HyphaApp/hypha/pull/3457
- [x]  Add rate limit https://github.com/HyphaApp/hypha/pull/3493

**Comment by theskumar** [comment]
> If a user has an existing account, the user should be routed to the login page
@fourthletter IMO, I would strongly advise not to put this requirement in the current registration flow. The current error is very explicit and widely adopt pattern to say that user account already exist and then user need to manual decide if they want to register using a different email or would like to login using that email.

Are you able to remove auto redirect to login as feature from this request please. 

>  Person registering receives instructions on the length of the password
This is show during the account activations and password change form. So it's not very specific to registration itself. @fourthletter @frjo do you have have specific wording or functionality in mind that you would like to implement.

**Comment by theskumar** [comment]
@fourthletter  Other request in this issue has been added to the PR #3457 please take a look at the screenshot attached, and see if they all make sense. 

PS: That PR requires the https://github.com/HyphaApp/hypha/pull/3432 to be merged first, as it built on top of the changes introduced to the authentication and registration during the nav removal.
