### ISSUE TITLE
[Epic] Dashboard design updates

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3591]
**Applicant Dashboard**
- [x] Update status bar UI, make every status visible upfront.
- [x] Update applicant dashboard header UI.
- [x] For the applicant dashboard, use the status bar for both projects and submissions.
- [x] Add only the active invoices as rows to the applicant dashboard with a few columns(as per the design).
- [x] Maintain a different type of invoice statuses, just to show invoice's current status only for invoice table/rows purposes not to list/history of the statuses.
- [x] #3628
- [x] #3792 
- [x] Update applicant dashboard UI, font sizes, spacing, text, and other things for submissions, projects, and invoices.

**Finance Dashboard**

- [x] My task module for finance members.
- [x] Overview section for count and quick access.
- [x] #3670
- [x] Use different tables/pages for PAF, reports, projects and invoices.

** Contracting Dashboard**

- [x] My task module for the contracting team members.
- [x] Overview section for count and quick access.

**Staff Dashboard**

- [x] My task module for the staff.
- [x] #3771
- [x] Rounds and Labs table

**Paf Approvers table**

- [x] My task module for the Paf approvers.
- [x] #3535

**Comment by sandeepsajan0** [comment]
Closing this as I created this to keep track of dashboard updates and we are finished with those updates.
