### ISSUE TITLE
Documentation updates/refactor

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3639]
## Description

The [Hypha documentation](https://docs.hypha.app/) is largely out of date and at times disjointed. As adopters of the application continue to grow and the code base gets older + larger, updating the documentation, making it easily maintainable, and regularly reviewing it for accuracy is critical.

## To-Do

- [x] All mentioned software versions should be made into [variables](https://mkdocs-macros-plugin.readthedocs.io/en/latest/#getting-started) so references in the docs are automatically updated.
- [x] Code formatting should be more consistent, and easily allow the user to copy & paste (ie. `$ ls` -> `ls`).
- [x] Installation tutorials should be retested with the latest OS versions.
- [x] Re-evaluate that documentation formatting follows the [Diataxis](https://diataxis.fr/) principles
- [x] Establish a time frame that ensures docs are reviewed on a regular basis (ie. Quarterly review & testing)
- [x] #3080
- [x] Add descriptions for [apply site](https://docs.hypha.app/getting-started/architecture/#apply-site) & [wagtail admin](https://docs.hypha.app/getting-started/architecture/#wagtail-admin)
- [x] Review and document [configuration](https://docs.hypha.app/setup/administrators/configuration/) feature flags
- [x] Review screenshots for accuracy (ie. [Using Wagtail Admin](https://docs.hypha.app/user-guides/creating-a-user-account/#using-wagtail-admin))
- [x] Update for password-less login features (ie. [How to login](https://docs.hypha.app/user-guides/creating-a-user-account/#using-wagtail-admin))
- [x] Initial [docstring documentation](https://pypi.org/project/mkgendocs/) implementation
- [x] [Setup notifications](https://docs.hypha.app/setup/setup-notifications/) needs to be populated
- [ ] Document the public web API
- [x] Update vulnerability disclosure instructions

**Comment by wes-otf** [comment]
Feel free to comment/edit the original checklist for anything else that should be added. Progress on this task can be found in the [enhancement/doc-improvements](https://github.com/HyphaApp/hypha/tree/enhancement/doc-improvements) branch.
